<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (ARREST_CHARGE_CODE,ARREST_CHA_DESC?,OFFENSE_CODE?)+>
  <!ELEMENT ARREST_CHARGE_CODE (#PCDATA)>
  <!ELEMENT ARREST_CHA_DESC (#PCDATA)>
  <!ELEMENT OFFENSE_CODE (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-2-2  C05</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>CRIMINAL RECKLESSNESS- OTHER</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-2-2  C05</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-2-2  C06</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>CRIMINAL RECKLESSNESS- OVERPASS</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-2-2  C06</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-2-2  C07</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>CRIMINAL RECKLESSNESS- PHYSICAL</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-2-2  C07</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-2-2  C08</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>CRIMINAL RECKLESSNESS- VEHICLE</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-2-2  C08</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-2-4</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>OBSTRUCTION OF TRAFFIC</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-2-4</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-2-5</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>MISCHIEF- OVERPASS</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-2-5</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-2-5.5</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>MISCHIEF- RAILROAD</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-2-5.5</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-2-6</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>BATTERY- BODY WASTE</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-2-6</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-2-7</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>TATTOO/PIERCE A MINOR</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-2-7</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-2-8</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>OBSTRUCTING PRESCRIPTION DRUG DELIVERY</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-2-8</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>9-30-5-4</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>MOTOR VEHICLE- OPERATING A VEHICLE WHILE INTOXICATED- BODILY INJURY</ARREST_CHA_DESC>
    <OFFENSE_CODE>9-30-5-4</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>9-30-5-5</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>MOTOR VEHICLE- OPERATING A VEHICLE WHILE INTOXICATED- CAUSING DEATH</ARREST_CHA_DESC>
    <OFFENSE_CODE>9-30-5-5</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>9-30-10-16</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>MOTOR VEHICLE- HABITUAL TRAFFIC VIOLATOR</ARREST_CHA_DESC>
    <OFFENSE_CODE>9-30-10-16</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>9-30-10-17</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>MOTOR VEHICLE- HABITUAL TRAFFIC VIOLATOR- LIFETIME</ARREST_CHA_DESC>
    <OFFENSE_CODE>9-30-10-17</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>9-31-2-26</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>MOTOR VEHICLE- WATERCRAFT TITLE VIOLATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>9-31-2-26</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>9-31-2-27</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>MOTOR VEHICLE- WATERCRAFT TITLE VIOLATION- FELONY</ARREST_CHA_DESC>
    <OFFENSE_CODE>9-31-2-27</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>10-14-3-29.5</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>PUBLIC SAFETY- VIOLATION OF LOCAL TRAVEL ADVISORY DESIGNATIONS</ARREST_CHA_DESC>
    <OFFENSE_CODE></OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-2-9</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>STRANGULATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-2-9</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-3-2</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>KIDNAPPING</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-3-2</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-3-3</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>CONFINEMENT</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-3-3</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-3-4</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>INTERFERENCE WITH CUSTODY</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-3-4</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-3.5-1A</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>HUMAN/SEXUAL TRAFFICKING- PROMOTION OF HUMAN TRAFFICKING</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-3.5-1A</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-3.5-1B</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>HUMAN/SEXUAL TRAFFICKING- SEXUAL TRAFFICKING OF A MINOR </ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-3.5-1B</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-3.5-1C</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>HUMAN/SEXUAL TRAFFICKING- HUMAN TRAFFICKING</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-3.5-1C</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-1  R01</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>RAPE- ARMED</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-1  R01</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-1  R02</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>RAPE- ATTEMPTED</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-1  R02</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-1  R03</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>RAPE- MENTAL PATIENT</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-1  R03</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-1  R04</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>RAPE- PRIS0NER</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-1  R04</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-1  R05</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>RAPE- UNARMED</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-1  R05</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-2</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>SEX CRIME- CRIMINAL DEVIATE CONDUCT</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-2</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-3</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>SEX CRIME- CHILD MOLEST</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-3</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-6</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>SEX CRIME- CHILD SOLICITATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-6</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-7</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>SEX CRIME- CHILD SEDUCTION</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-7</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-8</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>SEX CRIME- SEXUAL BATTERY</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-8</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-9</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>SEX CRIME- SEXUAL MISCONDUCT WITH MINOR</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-9</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-10</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>SEX CRIME- UNLAWFUL EMPLOYMENT NEAR CHILDREN BY SEXUAL PREDATOR/OFFENDER AGAINST CHILDREN</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-10</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-11</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>SEX CRIME- SEX OFFENDER RESIDENCY VIOLATIONS</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-11</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-12</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>SEX CRIME- SEX OFFENDER INTERNET OFFENSES</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-12</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-13</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>SEX CRIME- INAPPROPRIATE COMMUNICATION WITH A CHILD</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-13</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R01</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- ATTEMPTED</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R01</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R02</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- AUTO DEALER</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R02</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R03</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- BANK</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R03</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R04</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- CHECK CASHING STORE</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R04</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R05</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- CITY OFFICE</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R05</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R06</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- DOCTORS OFFICE</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R06</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R07</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- FEDERAL FINANCIAL INSTITUTION</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R07</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R08</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- FEDERAL OFFICE</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R08</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R09</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- GAS STATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R09</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R10</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- GROCERY STORE</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R10</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R11</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- HOSPITAL</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R11</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R12</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- HOTEL/MOTEL</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R12</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R13</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- INDUSTRIAL</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R13</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R14</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- LIQUOR STORE</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R14</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R15</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- MANUFACTURING </ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R15</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R16</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- MOTORIST</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R16</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R17</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- OTHER</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R17</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R18</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- PARKING GARAGE</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R18</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R19</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- PERSON</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R19</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R20</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- PHARMACY</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R20</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R21</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- POST OFFICE</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R21</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R22</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- RECREATIONAL/SPORTS</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R22</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R23</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- RESIDENCE</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R23</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R24</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- RESTAURANT</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R24</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R25</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- RETAIL</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R25</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R26</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- STATE OFFICE</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R26</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R27</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- TAVERN/CLUB</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R27</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R28</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- UTILITY OFFICE</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R28</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-1  R29</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ROBBERY- VFW</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-1  R29</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-5-2</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>CAR JACKING</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-5-2</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-43-1-1</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ARSON- ATTEMPTED</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-43-1-1</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-43-1-1A&#40;4&#41;</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ARSON- CHURCH/RELIGIOUS WORSHIP STRUCTURE</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-43-1-1A&#40;4&#41;</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-43-1-1B</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ARSON- FOR HIRE</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-43-1-1B</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-43-1-1A&#40;2&#41;</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ARSON- PROPERTY</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-43-1-1A&#40;2&#41;</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-43-1-1A&#40;1&#41;</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ARSON- RESIDENCE/DWELLING</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-43-1-1A&#40;1&#41;</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-43-1-1A</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ARSON- VEHICLE</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-43-1-1A</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-43-1-2A</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>CRIMINAL MISCHIEF</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-43-1-2A</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-43-1-2B</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>CRIMINAL MISCHIEF- INSTITUTIONAL </ARREST_CHA_DESC>
    <OFFENSE_CODE>35-43-1-2B</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-43-1-2.1</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>CRIMINAL MISCHIEF- CEMETARY</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-43-1-2.1</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-43-1-3</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>CRIMINAL MISCHIEF- CAVE</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-43-1-3</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-43-1-4</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>COMPUTER TAMPERING</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-43-1-4</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-43-1-5</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>WATER SUPPLY TAMPERING/POISONING </ARREST_CHA_DESC>
    <OFFENSE_CODE>35-43-1-5</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>11-8-8-15</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>CORRECTION- SEX OFFENDER FAIL TO POSSESS INDIANA DRIVERS LICENSE OR IDENTIFICATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>11-8-8-15</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>11-8-8-17</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>CORRECTION- SEX OFFENDER REGISTRATION VIOLATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>11-8-8-17</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>11-8-8-18</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>CORRECTION- SEXUAL VIOLENT PREDATOR DUTY TO NOTIFY VIOLATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>11-8-8-18</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>12-32-1-7</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>HUMAN SERVICES- FALSE STATEMENT FOR PUBLIC BENEFITS</ARREST_CHA_DESC>
    <OFFENSE_CODE>12-32-1-7</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>13-30-2-1</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ENVIRONMENT- ENVIRONMENTAL ACT VIOLATIONS </ARREST_CHA_DESC>
    <OFFENSE_CODE>13-30-2-1</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>13-30-10-5</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ENVIRONMENT- UNDERGROUND STORAGE TANK VIOLATIONS</ARREST_CHA_DESC>
    <OFFENSE_CODE>13-30-10-5</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>13-30-10-6</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>ENVIRONMENT- STATE REGULATED WETLAND LAW VIOLATIONS</ARREST_CHA_DESC>
    <OFFENSE_CODE>13-30-10-6</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-9-8-19</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- OBSTRUCT/HINDER/INTERFERE WITH OFFICER</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-9-8-19</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-15-4-1</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- WATERCRAFT CRASH- DUTIES OF OPERATORS</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-15-4-1</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-15-4-2</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- WATERCRAFT CRASH- DUTIES OF REPORTING</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-15-4-2</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-15-4-3</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- WATERCRAFT CRASH- DUTIES OF OCCUPANTS</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-15-4-3</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-15-8-8</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- OPERATION OF A MOTORBOAT WHILE INTOXICATED</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-15-8-8</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-15-8-9</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- OPERATION OF A MOTORBOAT IN VIOLATION OF ORDER</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-15-8-9</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-15-9-4</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- DIVER DOWN FLAG DISPLAY VIOLATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-15-9-4</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-15-9-5A</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- OPERATE A WATERCRAFT WITHING 150 FEET OF DIVER DOWN FLAG</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-15-9-5A</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-15-9-5B</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- OBJECTS IN WATER WITHIN 100 FEET OF DIVER DOWN FLAG</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-15-9-5B</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-15-9-6</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- DIVING WITHIN 150 FEET OF ANCHORED WATERCRAFT</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-15-9-6</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-15-9-7</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- DIVER SURFACING WITHIN 100 FEET FROM DIVER DOWN FLAG</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-15-9-7</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-15-11-11</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- OPERATE A MOTORBOAT WHILE LICENSE SUSPENDED</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-15-11-11</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-15-12-10</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- REASONABLE/PRUDENT WATERCRAFT OPERATION VIOLATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-15-12-10</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-16-1-17</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- ALTERED VIN ON OFF-ROAD VEHICLE</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-16-1-17</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-16-1-18</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- DUTIES OF DEALERS OF OFF-ROAD VEHICLES</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-16-1-18</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-16-1-23</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- OPERATE OFF-ROAD VEHICLE UNDER INFLUENCE </ARREST_CHA_DESC>
    <OFFENSE_CODE>14-16-1-23</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-16-1-24</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- OFF-ROAD VEHICLE CRASH- DUTIES OF REPORTING</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-16-1-24</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-17-4-8</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- OPEN FIRE PERMIT VIOLATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-17-4-8</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-20-1-25</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- ALTER HISTORIC STATE PROPERTY</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-20-1-25</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-21-1-16</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- HISTORIC PROPERTY INVESTIGATION VIOLATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-21-1-16</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-21-1-26</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- DISTURB GROUND FOR ARTIFACTS/REMAINS/OBJECTS</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-21-1-26</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-21-1-26.5</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- DISTURB GROUND WITHIN 100 FEET OF BURIAL GROUND</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-21-1-26.5</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-21-1-28</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- DISTURB HUMAN REMAINS OR GRAVE MARKERS</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-21-1-28</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-21-1-36</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- POSSESS LOOTED PROPERTY</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-21-1-36</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-21-2-3</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- GRAVE MEMORIAL REMOVAL VIOLATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-21-2-3</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-21-2-4</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- PURCHASE/SALE OF ITEMS REMOVED FROM CEMETERY</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-21-2-4</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-6-1</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- UNLAWFUL TAKING OF WILD ANIMALS</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-6-1</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-6-2</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- UNLAWFUL TAKING OF MIGRATORY BIRDS</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-6-2</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-6-3</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- MIGRATORY BIRD PERMIT/LICENSE VIOLATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-6-3</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-6-4</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- TRAPPING/TENDING TRAPS VIOLATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-6-4</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-6-6</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- TRAPPING WITH SNARE VIOLATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-6-6</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-6-7</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- JACKLIGHTING- ARTIFICIAL LIGHT VIOLATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-6-7</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-6-8</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- WILD BIRD/MAMMAL SALE VIOLATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-6-8</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-6-9</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- SHOOTING FROM/ACROSS A PUBLIC HIGHWAY </ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-6-9</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-6-10</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- SHOOTING INTO/ACROSS WATERS OF THE STATE</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-6-10</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-6-11</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- POSSESS AND/OR USE OF SILENCER WHILE HUNTING</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-6-11</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-7-3</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- MIGRATORY WATERFOWL STAMP VIOLATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-7-3</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-9-1</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- UNLAWFUL MEANS OF TAKING FISH</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-9-1</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-9-2</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- ICE FISHING VIOLATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-9-2</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-9-3</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- UNLAWFUL FISHING NEAR DAMS</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-9-3</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-9-4</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- UNLAWFUL TRANSPORT OF MINNOWS/CRAYFISH</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-9-4</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-9-5</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- TRANSPORT MINNOWS/CRAYFISH OUTSIDE OF STATE</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-9-5</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-9-6</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- FISHING WASTE DISPOSAL VIOLATIONS IN/NEAR WATERS OF LAKE MICHIGAN</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-9-6</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>14-22-9-7</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>NATURAL RESOURCE- UNLAWFUL SALE OF FISH</ARREST_CHA_DESC>
    <OFFENSE_CODE>14-22-9-7</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-4B</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>SEX CRIME- CHILD EXPLOITATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-4B</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-4C</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>SEX CRIME- POSSESS CHILD PORNOGRAPHY</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-4C</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-5</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>SEX CRIME- VICARIOUS SEXUAL GRATIFICATION</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-5</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <ARREST_CHARGE_CODE>35-42-4-5C</ARREST_CHARGE_CODE>
    <ARREST_CHA_DESC>SEX CRIME- PERFORMING SEXUAL CONDUCT IN THE PRESENSE OF A MINOR</ARREST_CHA_DESC>
    <OFFENSE_CODE>35-42-4-5C</OFFENSE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>