<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (CODE_TYPE,CODE,DESCRIPTION?)+>
  <!ELEMENT CODE_TYPE (#PCDATA)>
  <!ELEMENT CODE (#PCDATA)>
  <!ELEMENT DESCRIPTION (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>01</CODE>
    <DESCRIPTION>Air/Bus/Train Terminal</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>02</CODE>
    <DESCRIPTION>Bank/Savings And Loan</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>03</CODE>
    <DESCRIPTION>Bar/Night Club</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>04</CODE>
    <DESCRIPTION>Church/Synagogue/Temple</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>05</CODE>
    <DESCRIPTION>Commercial/Office Building</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>06</CODE>
    <DESCRIPTION>Construction Site</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>07</CODE>
    <DESCRIPTION>Convenience Store</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>08</CODE>
    <DESCRIPTION>Department/Discount Store</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>09</CODE>
    <DESCRIPTION>Drug Store/Doctors Office/Hospital</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>10</CODE>
    <DESCRIPTION>Field/Woods</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>11</CODE>
    <DESCRIPTION>Government/Public Building</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>12</CODE>
    <DESCRIPTION>Grocery/Supermarket</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>13</CODE>
    <DESCRIPTION>Highway/Road/Alley</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>14</CODE>
    <DESCRIPTION>Hotel/Motel/Etc.</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>15</CODE>
    <DESCRIPTION>Jail/Prison</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>16</CODE>
    <DESCRIPTION>Lake/Waterway</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>17</CODE>
    <DESCRIPTION>Liquor Store</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>18</CODE>
    <DESCRIPTION>Parking Lot/Garage</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>19</CODE>
    <DESCRIPTION>Rental Storage Facility</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>20</CODE>
    <DESCRIPTION>Residence/Home</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>21</CODE>
    <DESCRIPTION>Restaurant</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>22</CODE>
    <DESCRIPTION>School/College &#40;Includes University&#41;</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>23</CODE>
    <DESCRIPTION>Service/Gas Station</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>24</CODE>
    <DESCRIPTION>Specialty Store</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>25</CODE>
    <DESCRIPTION>Other/Unknown</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>37</CODE>
    <DESCRIPTION>Abandoned/Condemned Structure</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>38</CODE>
    <DESCRIPTION>Amusement Park</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>39</CODE>
    <DESCRIPTION>Arena/Stadium/Fairgrounds/Coliseum</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>40</CODE>
    <DESCRIPTION>ATM Machine Separate from Bank</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>41</CODE>
    <DESCRIPTION>Auto Dealership New/Used</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>42</CODE>
    <DESCRIPTION>Camp/Campground</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>43</CODE>
    <DESCRIPTION>Cargo Container</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>44</CODE>
    <DESCRIPTION>Daycare Facility</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>45</CODE>
    <DESCRIPTION>Dock/Wharf/Freight/Modal Terminal</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>46</CODE>
    <DESCRIPTION>Farm Facility</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>47</CODE>
    <DESCRIPTION>Gambling Facility/Casino/Race Track</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>48</CODE>
    <DESCRIPTION>Industrial Site</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>49</CODE>
    <DESCRIPTION>Military Installation</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>50</CODE>
    <DESCRIPTION>Park/Playground</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>51</CODE>
    <DESCRIPTION>Rest Area</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>52</CODE>
    <DESCRIPTION>School-College/University</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>53</CODE>
    <DESCRIPTION>School-Elementary/Secondary</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>54</CODE>
    <DESCRIPTION>Shelter-Mission/Homeless</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>55</CODE>
    <DESCRIPTION>Shopping Mall</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>56</CODE>
    <DESCRIPTION>Tribal Lands</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>57</CODE>
    <DESCRIPTION>Community Center</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>58</CODE>
    <DESCRIPTION>Cyberspace</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>PLACE_CODES</CODE_TYPE>
    <CODE>90</CODE>
    <DESCRIPTION>Gaming Establishment</DESCRIPTION>
  </DATA_RECORD>
</main>
