<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (OFFENSE_CODE,OFFENSE_DESC?)+>
  <!ELEMENT OFFENSE_CODE (#PCDATA)>
  <!ELEMENT OFFENSE_DESC (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <OFFENSE_CODE>4-30-14-5</OFFENSE_CODE>
    <OFFENSE_DESC>LOTTERY- UNLAWFUL REPRESENTATION AS RETAILER</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>4-30-14-6</OFFENSE_CODE>
    <OFFENSE_DESC>LOTTERY- UNLAWFUL REPRESENTATION OF ENTERPRISE AS STATE LOTTERY</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>4-33-10-1</OFFENSE_CODE>
    <OFFENSE_DESC>RIVERBOAT GAMBLING- UNLAWFUL ENTRY INTO CASINO</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-1-1</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- DEFACE, FALSIFY, DESTROY DECLARATIONS/REQUESTS/PETITIONS/CERTIFICATES</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-1-3</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- FAIL TO MAKE PUBLIC DISCLAIMER ON CIRCULATIONS/PUBLICATIONS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-1-6</OFFENSE_CODE>
    <OFFENSE_DESC>Election- Law Enforcement/Firefighter Solicitation/Election Functions While In Unifor m</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-1-10</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- ILLEGAL POLITICAL CONTRIBUTION VIOLATIONS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-1-11</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- MAKING/ACCEPTING POLITICAL CONTRIBUTIONS IN NAME OF ANOTHER PERSON</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-1-13</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- FILING FRAUDULENT REPORTS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-1</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- FRAUDULENT APPLICATION FOR REGISTRATION OR ABSENTEE BALLOT/FRAUDULENT VOTING</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-2</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- FRAUDULENT VOTER REGISTRATION VIOLATIONS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-2.5</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- FRAUDULENT SOLICITATION OF ABSENTEE BALLOT APPLICATIONS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-4</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- REGISTERING TO VOTE MORE THAN ONCE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-5</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- DESTROY, FAIL TO FILE OR DELIVER, REGISTRATION OR ABSENTEE BALLOT APPLICATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-6</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- UNAUTHORIZED RELEASE OR REMOVAL OF REGISTRATION MATERIALS/INFORMATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-7</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- WITHHOLDING/FURNISHING FALSE INFORMATION TO POLL TAKER</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-8</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- POLL TAKER RETURN OF NAMES OF INELIGIBLE, FICTITIOUS, OR DECEASED PERSONS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-9</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- UNREGISTERED OR UNAUTHORIZED VOTING</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-10</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- VOTING BY INELIGIBLE PERSONS- ILLEGAL VOTING</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-11</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- VOTING AT WRONG PRECINCT</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-12</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- VOTING UNDER FALSE NAME</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-13</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- HIRING/SOLICITING INELIGIBLE PERSON TO VOTE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-14</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- PRECINT OFFICER/PUBLIC OFFICIAL ALLOWING INELIGIBLE VOTERS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-15</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- UNAUTHORIZED DELIVERY OF BALLOTS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-16</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- FRAUDULENT APPLICATION/SHOWING/RECEIPT/POSSESSION/COMPLETION/DELIVERY OF BALLOTS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-17</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- MARKING BALLOT TO INDICATE TO ANOTHER HOW VOTER HAS VOTED</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-19</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- FORGERY OF OFFICIAL BALLOT</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-20</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- DECEPTIVE REGISTRATION OF VOTE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-21</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- FRAUDULENT INDUCEMENT TO VOTE OTHER THAN AS INTENDED</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-22</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- FALSE REPRESENTATION OF BALLOT TO NON-ENGLISH SPEAKING VOTER</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-23</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- OPEN, DESTROY, OR IMPROPER DELIVERY OF BALLOTS BY CUSTODIAN OF BALLOTS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-24</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- REMOVE, DESTROY BALLOTS/FALSE ENTRY IN POLL BOOK/FALSE TALLY</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-25</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- MARKING/DEFACING BALLOTS BY PRECINCT BOARD MEMBER</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-26</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- TAMPERING WITH BALLOT CONTAINER/VOTING SYSTEM COMPONENT OR CONTENTS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-27</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- FRAUDULENT RECORDING OF VOTES BY PRECINCT ELECTION OFFICER</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-28</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- FRAUDULENT ALTERATION OF ELECTION RETURN/POLL BOOK/TALLY/VOTING RETURNS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-29</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- INSPECTING VOTING SYSTEM WITHOUT AUTHORIZATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-3-4</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- OBSTRUCT, INTERFERE, OR INJURE A VOTER OR ELECTION OFFICER</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-3-7</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- MUTILATING VOTING SYSTEMS TO DECEIVE VOTERS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-3-8</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- DAMAGE, DISARRANGE, OR TAMPER WITH VOTING SYSTEM</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-3-15</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- UNAUTHORIZED ENTRIES AT POLLS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-3-19</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- INDUCING VOTES BY GIFT OR OFFER OF COMPENSATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-3-20</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- ACCEPT/SOLICIT COMPENSATION TO INDUCE OR PROCURE VOTES</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-3-21</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- INFLUENCING POLICITAL OPINIONS/ACTIONS OF EMPLOYEES IN WORKPLACE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>3-14-2-21.5</OFFENSE_CODE>
    <OFFENSE_DESC>ELECTION- VOTER INTIMIDATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>4-30-12-4</OFFENSE_CODE>
    <OFFENSE_DESC>LOTTERY- UNLAWFUL PURCHASE OF TICKETS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>4-30-13-1</OFFENSE_CODE>
    <OFFENSE_DESC>LOTTERY- UNLAWFUL SALE OF TICKETS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>4-30-14-2</OFFENSE_CODE>
    <OFFENSE_DESC>LOTTERY- UNLAWFUL REPRESENTATION OF PRIZE WINNER</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>4-30-14-3</OFFENSE_CODE>
    <OFFENSE_DESC>LOTTERY- UNLAWFUL COUNTERFEIT OR ALTER OF TICKETS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>4-30-14-4</OFFENSE_CODE>
    <OFFENSE_DESC>LOTTERY- UNLAWFUL DISCLOSURE OF CONFIDENTIAL LOTTERY INFORMATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>35-43-5-7</OFFENSE_CODE>
    <OFFENSE_DESC>FRAUD- WELFARE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>35-43-5-7.1</OFFENSE_CODE>
    <OFFENSE_DESC>FRAUD- MEDICAID</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>35-43-5-7.2</OFFENSE_CODE>
    <OFFENSE_DESC>FRAUD- CHILDREN HEALTH INSURANCE PROGRAM</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>4-33-10-2</OFFENSE_CODE>
    <OFFENSE_DESC>RIVERBOAT GAMBLING- CASINO GAMBLING VIOLATIONS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>5-2-4-7</OFFENSE_CODE>
    <OFFENSE_DESC>PUBLIC OFFICIAL/LAW ENFORCEMENT- UNLAWFUL DISCLOSURE OF CRIMINAL INTELLIGENCE INFORMATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>5-13-14-3</OFFENSE_CODE>
    <OFFENSE_DESC>PUBLIC FUND- PUBLIC OFFICER FAIL TO DEPOSIT PUBLIC FUNDS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>5-13-14-4</OFFENSE_CODE>
    <OFFENSE_DESC>PUBLIC FUND- PUBLIC OFFICER FAIL TO PERFORM DUTY</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>5-14-3-10</OFFENSE_CODE>
    <OFFENSE_DESC>PUBLIC RECORD- UNAUTHORIZED RELEASE OF PROTECTED INFORMATION BY PUBLIC OFFICIAL</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>5-15-6-8</OFFENSE_CODE>
    <OFFENSE_DESC>PUBLIC RECORD- UNAUTHORIZED DESTRUCTION OF PUBLIC RECORDS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>6-1.1-5.5-10</OFFENSE_CODE>
    <OFFENSE_DESC>TAXATION- FALSIFY VALUE OF TRANSFERRED REAL PROPERTY</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>6-1.1-37-2</OFFENSE_CODE>
    <OFFENSE_DESC>TAXATION- ASSESSMENT VIOLATIONS BY PUBLIC OFFICIALS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>6-1.1-37-3</OFFENSE_CODE>
    <OFFENSE_DESC>TAXATION- FALSE INFORMATION ON PROPERTY TAX RETURN</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>6-6-1.1-1313</OFFENSE_CODE>
    <OFFENSE_DESC>TAXATION- GASOLINE TAX EVASION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>6-6-2.5-62</OFFENSE_CODE>
    <OFFENSE_DESC>TAXATION- SPECIAL FUEL, DYED OR MARKER, VIOLATIONS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>6-7-1-21</OFFENSE_CODE>
    <OFFENSE_DESC>TAXATION- SALE OF CIGARETTES WITH COUNTERFEIT TAX STAMP</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>6-7-1-24</OFFENSE_CODE>
    <OFFENSE_DESC>TAXATION- POSSESS OR SALE OF CIGARETTES WITHOUT TAX STAMP</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>6-7-2-21</OFFENSE_CODE>
    <OFFENSE_DESC>TAXATION- TOBACCO DISTRIBUTOR VIOLATIONS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-3-1-14</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- SUNDAY ALCOHOL SALE VIOLATIONS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-3-10-10</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- DISREGARD ORDER TO CEASE SALES</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-3-26-15</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- DIRECT WINE SELLER VIOLATIONS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-1-3</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- PUBLIC INTOXICATION BY ALCOHOL/DRUGS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-1-6</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- INTOXICATION UPON A COMMON CARRIER</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-1-12</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- VIOLATION OF COMMISSION ORDER</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-4-1</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- POSSESS UNTAXED BEVERAGE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-4-3</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- UNLAWFUL FURNISH EVIDENCE OF TAX PAYMENT OR PERMIT ISSUANCE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-4-6</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- FRAUDULENT STATEMENT OF TAX PAYMENT</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-6-1</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- MAKE ALCOHOLIC BEVERAGE WITHOUT PERMIT</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-6-4</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- PROVIDE FALSE RECORD TO COMMISSION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-7-1</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- MINOR PROVIDE FALSE STATEMENT OF AGE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-7-2</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- PROVIDE FALSE IDENTITY OF AGE TO MINOR</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-7-7</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- MINOR POSSESS ALCOHOL</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-7-8</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- PROVIDE ALCOHOL TO A MINOR</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-7-10A</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- MINOR IN A TAVERN</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-7-10B</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- ALLOWING MINOR IN A TAVERN</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-7-12</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- EMPLOY MINOR WHERE ALCOHOL PROVIDED</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-7-14</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- NOTICE FROM PARENT VIOLATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-8-1</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- HINDER OR PREVENT ENFORCEMENT OF TITLE 7.1</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-8-3</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- WOOD ALCOHOL AS BEVERAGE PROHIBITED</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-8-5</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- TAKING ALCOHOL INTO A LICENSED PREMISE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-8-6</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- TAKING/CONSUMING LIQUOR IN RESTAURANT</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-8-9</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- PURCHASE BEER FROM UN-BONDED BREWERY</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-9-1</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- PROHIBITED INTEREST BY COMMISSION MEMBER</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-9-2</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- PROHIBITED INTEREST BY BREWER/VINTNER</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-9-3</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- PROHIBITED INTEREST BY BEER PERMITTEE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-9-4</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- PROHIBITED INTEREST BY ANOTHER PERMIT</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-9-6</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- PROHIBITED INTEREST BY LIQUOR PERMITTEE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-9-7</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- PROHIBITED INTEREST BY DISTILLER/RECTIFIER</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-9-9</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- PROHIBITED INTEREST BY WHOLESALER</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-9-10</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- PROHIBITED INTEREST BY RETAILER</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-9-12</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- WAREHOUSE USE VIOLATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-9-14</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- SALE TO A NON-PERMITTEE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-9-15</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- MANAGER QUESTIONNAIRE VIOLATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-10-10</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- HUCKSTERING- DELIVER ALCOHOLIC BEVERAGE WITHOUT AN ORDER</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-10-15</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- SALE OF ALCOHOL TO INTOXICATED PERSON</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-10-21</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- VISIT/MAINTAIN ALCOHOLIC BEVERAGE COMMON NUISANCE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-10-23</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- SELL OFF PREMISE/PROOF OF AGE </OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-11-1</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- IMPORTATION OF LIQUOR VIOLATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-11-1.5</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- SHIPMENTS TO NON-PERMITTED WHOLESALER</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-11-2</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- CARRIER TRANSPORT WITHOUT PERMIT</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-11-3</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- CARRIER TRANSPORT IN UNREGISTERED VEHICLE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-11-4</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- LIMITED DELIVERY VIOLATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-11-5</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- TRANSPORT UNTAXED BEVERAGE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-11-6</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- DEVIOUS TRANSPORTATION TO AVOID TAX</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-11-14B</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- COUNTERFEIT/CHANGE/PREDATE A LICENSE/PERMIT</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-12-14</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- EXCESS OR INSUFFICIENT CHARGE FOR LICENSE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-13-5</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- POSSESS SEINE/NET/COMMERCIAL FISH GEAR</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-13-7</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- COMMERCIAL TAKING/SALE OF FISH FROM OHIO RIVER</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-17-2</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- MUSSEL/MUSSEL SHELL LICENSE VIOLATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-19-1</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- FURBEARING MAMMAL/HIDE/FUR PURCHASE VIOLATION </OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-23-1</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- FALCONRY PRACTICE WITHOUT LICENSE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-23-5</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- FALCONRY LICENSE/STAMP VIOLATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-24-1</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- FIELD TRIAL PERMIT VIOLATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-24-4</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- FIELD TRIAL OUT OF SEASON VIOLATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-25-2</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- IMPORTATION OF FISH/WILD ANIMAL VIOLATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-30-1</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- UNLAWFUL USE OF EXPLOSIVES IN STATE WATERS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-31-1</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- SHOOTING PRESERVE LICENSE VIOLATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-31-3</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- SHOOTING PRESERVE RESTRICTION VIOLATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-32-2</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- TAKE GAME BIRD/EXOTIC MAMMAL BY UNAPPROVED MEANS </OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-34-9</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- UNLAWFUL TAKING/POSSESS OF NONGAME SPECIES</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-34-12</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- UNLAWFUL TAKING/POSSESS OF ENDANGERED SPECIES</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-37-2</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- INTERFERE WITH THE LEGAL TAKING OF A GAME ANIMAL</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-37-3</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- FAIL TO OBEY LAW OFFICER TO DESIST INTERFERENCE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-38-3</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- UNLAWFUL TAKING OF DEER OR WILD TURKEY</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-38-6</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- UNLAWFUL SALE/SHIPMENT OF WILD ANIMAL/NEST/EGG</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-22-40-6</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- UNLAWFUL SHOOTING AT LAW ENFORCEMENT DECOYS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-23-7-5</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- OPEN BURNING IN EMERGENCY FIRE HAZARD AREA</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-24-11-4</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- DISTURB AN APIARY/HONEYBEE HIVE/COLONY/HABITAT</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-26-7-5</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- INTERFERE WITH DAM/BANK/LEVEE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-26-7-6</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- INTERFERE WITH BANK/SHORE OF FRESHWATER LAKE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-26-7-7</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- ALTER DAM/SPILLWAY/OUTLET TO A LAKE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-29-8-5&#40;1&#41;</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- LITTERING IN WATER OR ON BANK OF A STREAM</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-29-8-5&#40;2&#41;</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- TRESPASS- CROSSING PRIVATE LAND TO ACCESS STREAM</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-31-3-15</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- DEALING GINSENG WITHOUT A LICENSE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-31-3-16</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- HARVESTING GINSENG OUT OF SEASON</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-31-3-17</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- POSSESS UNPROCESSED GINSENG OUT OF SEASON</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-31-3-19</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- DEALING GINSENG OUT OF SEASON</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-31-3-20</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- EXPORTING GINSENG OUT OF SEASON</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-31-3-21</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- GINSENG HARVESTED OUT OF STATE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-34-16-6</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- MINING PERMIT/CONDITIONS VIOLATIONS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-37-7-7</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- POLLUTION OF DRINKING WATER BY DRILLING</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-37-8-1</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- WELL PLUGGING/ABANDONMENT VIOLATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>14-37-8-3</OFFENSE_CODE>
    <OFFENSE_DESC>NATURAL RESOURCE- WELL SEALING/CAPPING VIOLATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>15-16-1-14</OFFENSE_CODE>
    <OFFENSE_DESC>AGRICULTURE/ANIMAL- ANHYDROUS AMMONIA DISTRIBUTION VIOLATIONS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>15-17-18-3</OFFENSE_CODE>
    <OFFENSE_DESC>AGRICULTURE/ANIMAL- SALE OR TRANSFER OF DISEASED ANIMAL</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>15-17-18-4</OFFENSE_CODE>
    <OFFENSE_DESC>AGRICULTURE/ANIMAL- TRANSPORT DISEASED CATTLE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>15-17-18-6</OFFENSE_CODE>
    <OFFENSE_DESC>AGRICULTURE/ANIMAL- IMPORT DISEASED DOMESTIC ANIMAL</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>15-17-18-7</OFFENSE_CODE>
    <OFFENSE_DESC>AGRICULTURE/ANIMAL- TRANSPORT DISEASED DOMESTIC ANIMAL</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>15-17-18-8</OFFENSE_CODE>
    <OFFENSE_DESC>AGRICULTURE/ANIMAL- LIVESTOCK OR POULTRY RUNNING AT-LARGE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>15-19-3-4</OFFENSE_CODE>
    <OFFENSE_DESC>AGRICULTURE/ANIMAL- UNAUTHORIZED HORSE RACING</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>15-19-3-5</OFFENSE_CODE>
    <OFFENSE_DESC>AGRICULTURE/ANIMAL- UNLAWFUL ACTS TO AFFECT HORSE PERFORMANCE DURING RACE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>15-20-1-4</OFFENSE_CODE>
    <OFFENSE_DESC>AGRICULTURE/ANIMAL- FAIL TO RESTRAIN A DOG RESULTING IN BITE OR ATTACK</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>16-42-19-11</OFFENSE_CODE>
    <OFFENSE_DESC>HEALTH- DEALING/IMPROPER SALE OF A LEGEND DRUG</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>16-42-19-12</OFFENSE_CODE>
    <OFFENSE_DESC>HEALTH- IMPROPER REFILL OF A LEGEND DRUG PRESCRIPTION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>16-42-19-13</OFFENSE_CODE>
    <OFFENSE_DESC>HEALTH- POSSESS LEGEND DRUG OR PRECURSOR</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>16-42-19-14</OFFENSE_CODE>
    <OFFENSE_DESC>HEALTH- MANUFACTURER/WHOLESALER FAIL TO KEEP LEGEND DRUG RECORDS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>16-42-19-15</OFFENSE_CODE>
    <OFFENSE_DESC>HEALTH- FAIL TO MAKE AVAILABLE LEGEND DRUG RECORDS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>16-42-19-16</OFFENSE_CODE>
    <OFFENSE_DESC>HEALTH- LEGEND DRUG FRAUD</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>16-42-19-17</OFFENSE_CODE>
    <OFFENSE_DESC>HEALTH- POSSESS INSTRUMENTS USED TO SMOKE LEGEND DRUGS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>16-42-19-18</OFFENSE_CODE>
    <OFFENSE_DESC>HEALTH- POSSESS HYPODERMIC SYRINGE OR NEEDLE</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>16-42-19-19</OFFENSE_CODE>
    <OFFENSE_DESC>HEALTH- POSSESS ANABOLIC STEROIDS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>16-42-19-20</OFFENSE_CODE>
    <OFFENSE_DESC>HEALTH- LEGEND DRUG PRESCRIPTION VIOLATION</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>16-42-19-24</OFFENSE_CODE>
    <OFFENSE_DESC>HEALTH- COMMON NUISANCE- LEGEND DRUG</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>16-42-19-25</OFFENSE_CODE>
    <OFFENSE_DESC>HEALTH- DEALING ANABOLIC STEROIDS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>22-11-14-6</OFFENSE_CODE>
    <OFFENSE_DESC>SAFETY- FIREWORKS REGULATION LAW VIOLATIONS</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-11-7</OFFENSE_CODE>
    <OFFENSE_DESC>ALCOHOLIC BEVERAGE- RECEIVE/SHIP FALSE SHIPMENT</OFFENSE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <OFFENSE_CODE>7.1-5-11-8</OFFENSE_CODE>