<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (ROLE_CODE,ROLE_DESC?)+>
  <!ELEMENT ROLE_CODE (#PCDATA)>
  <!ELEMENT ROLE_DESC (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <ROLE_CODE>R</ROLE_CODE>
    <ROLE_DESC>Reporting</ROLE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <ROLE_CODE>A</ROLE_CODE>
    <ROLE_DESC>Assisting</ROLE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <ROLE_CODE>I</ROLE_CODE>
    <ROLE_DESC>Investigating</ROLE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <ROLE_CODE>T</ROLE_CODE>
    <ROLE_DESC>Transporting</ROLE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <ROLE_CODE>C</ROLE_CODE>
    <ROLE_DESC>Crime Scene Tech</ROLE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <ROLE_CODE>X</ROLE_CODE>
    <ROLE_DESC>Arresting / Citing</ROLE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <ROLE_CODE>P</ROLE_CODE>
    <ROLE_DESC>Approving</ROLE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <ROLE_CODE>U</ROLE_CODE>
    <ROLE_DESC>UCR Validation</ROLE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <ROLE_CODE>Y</ROLE_CODE>
    <ROLE_DESC>Typist</ROLE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <ROLE_CODE>L</ROLE_CODE>
    <ROLE_DESC>Laboratory Technician</ROLE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <ROLE_CODE>D</ROLE_CODE>
    <ROLE_DESC>Dispatcher</ROLE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <ROLE_CODE>H</ROLE_CODE>
    <ROLE_DESC>Discharging</ROLE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <ROLE_CODE>F</ROLE_CODE>
    <ROLE_DESC>Debriefing</ROLE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <ROLE_CODE>G</ROLE_CODE>
    <ROLE_DESC>Detaining</ROLE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <ROLE_CODE>S</ROLE_CODE>
    <ROLE_DESC>Warrant Serving Officer</ROLE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <ROLE_CODE>B</ROLE_CODE>
    <ROLE_DESC>Citing</ROLE_DESC>
  </DATA_RECORD>
</main>
