<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (CODE_TYPE,CODE,DESCRIPTION?)+>
  <!ELEMENT CODE_TYPE (#PCDATA)>
  <!ELEMENT CODE (#PCDATA)>
  <!ELEMENT DESCRIPTION (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>A</CODE>
    <DESCRIPTION>SUSPECTED CRACK COCAINE</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>B</CODE>
    <DESCRIPTION>SUSPECTED COCAINE</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>C</CODE>
    <DESCRIPTION>SUSPECTED HASHISH</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>CD</CODE>
    <DESCRIPTION>CrazyDrug</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>D</CODE>
    <DESCRIPTION>SUSPECTED HEROIN</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>E</CODE>
    <DESCRIPTION>SUSPECTED MARIJUANA</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>F</CODE>
    <DESCRIPTION>SUSPECTED MORPHINE</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>G</CODE>
    <DESCRIPTION>SUSPECTED OPIUM</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>H</CODE>
    <DESCRIPTION>SUSPECTED OTHER NARCOTICS</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>I</CODE>
    <DESCRIPTION>SUSPECTED LSD</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>J</CODE>
    <DESCRIPTION>SUSPECTED PCP</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>K</CODE>
    <DESCRIPTION>SUSPECTED OTHER HALLUCINGENS</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>L</CODE>
    <DESCRIPTION>SUSPECTED METH/AMPHETAMINES</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>M</CODE>
    <DESCRIPTION>SUSPECTED OTHER STIMULANTS</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>N</CODE>
    <DESCRIPTION>SUSPECTED BARBITURATES</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>O</CODE>
    <DESCRIPTION>SUSPECTED OTHER DEPRESSANTS</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>P</CODE>
    <DESCRIPTION>SUSPECTED OTHER DRUGS</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>SCD</CODE>
    <DESCRIPTION>A SuperCrazyDrug</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>U</CODE>
    <DESCRIPTION>SUSPECTED UNKNOWN</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>DRUG_TYPE_CODES</CODE_TYPE>
    <CODE>X</CODE>
    <DESCRIPTION>SUSPECTED MORE THAN 3 TYPES</DESCRIPTION>
  </DATA_RECORD>
</main>
