<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (CODE_TYPE,CODE,DESCRIPTION?)+>
  <!ELEMENT CODE_TYPE (#PCDATA)>
  <!ELEMENT CODE (#PCDATA)>
  <!ELEMENT DESCRIPTION (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <CODE_TYPE>RESIDENT_STATUS_CODES</CODE_TYPE>
    <CODE>C</CODE>
    <DESCRIPTION>Resides in County but not City</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>RESIDENT_STATUS_CODES</CODE_TYPE>
    <CODE>O</CODE>
    <DESCRIPTION>Resides out of state</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>RESIDENT_STATUS_CODES</CODE_TYPE>
    <CODE>R</CODE>
    <DESCRIPTION>Resides in City where occurred</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>RESIDENT_STATUS_CODES</CODE_TYPE>
    <CODE>S</CODE>
    <DESCRIPTION>Resides in State but not City</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>RESIDENT_STATUS_CODES</CODE_TYPE>
    <CODE>U</CODE>
    <DESCRIPTION>Unknown</DESCRIPTION>
  </DATA_RECORD>
</main>
