<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (CODE_TYPE,CODE,DESCRIPTION?)+>
  <!ELEMENT CODE_TYPE (#PCDATA)>
  <!ELEMENT CODE (#PCDATA)>
  <!ELEMENT DESCRIPTION (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>AME</CODE>
    <DESCRIPTION>Amethyst &#40;purple&#41;</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>BARF</CODE>
    <DESCRIPTION>Barf</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>BGE</CODE>
    <DESCRIPTION>Beige</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>BLK</CODE>
    <DESCRIPTION>Black</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>BLU</CODE>
    <DESCRIPTION>Blue</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>BRO</CODE>
    <DESCRIPTION>Brown</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>BRZ</CODE>
    <DESCRIPTION>Bronze</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>CAM</CODE>
    <DESCRIPTION>Camouflage</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>COM</CODE>
    <DESCRIPTION>Chrome, Stainless Steel</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>CPR</CODE>
    <DESCRIPTION>Copper</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>CRM</CODE>
    <DESCRIPTION>Cream or Ivory</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>DBL</CODE>
    <DESCRIPTION>Blue, Dark</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>DGR</CODE>
    <DESCRIPTION>Green, Dark</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>GLD</CODE>
    <DESCRIPTION>Gold</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>GRN</CODE>
    <DESCRIPTION>Green</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>GRY</CODE>
    <DESCRIPTION>Gray</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>LAV</CODE>
    <DESCRIPTION>Lavender</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>LBL</CODE>
    <DESCRIPTION>Blue, Light</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>LGR</CODE>
    <DESCRIPTION>Green, Light</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>MAR</CODE>
    <DESCRIPTION>Burgundy or Maroon</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>MLT</CODE>
    <DESCRIPTION>Multicolored</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>MVE</CODE>
    <DESCRIPTION>Mauve &#40;purple&#41;</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>ONG</CODE>
    <DESCRIPTION>Orange</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>PLE</CODE>
    <DESCRIPTION>Purple</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>PNK</CODE>
    <DESCRIPTION>Pink</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>RED</CODE>
    <DESCRIPTION>Red</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>SIL</CODE>
    <DESCRIPTION>Aluminum, Silver</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>TAN</CODE>
    <DESCRIPTION>Tan</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>TEA</CODE>
    <DESCRIPTION>Teal &#40;green&#41;</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>TPE</CODE>
    <DESCRIPTION>Taupe &#40;brown&#41;</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>TRQ</CODE>
    <DESCRIPTION>Turquoise &#40;blue&#41;</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>WHI</CODE>
    <DESCRIPTION>White</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_COLOR_CODES</CODE_TYPE>
    <CODE>YEL</CODE>
    <DESCRIPTION>Yellow</DESCRIPTION>
  </DATA_RECORD>
</main>
