<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (VEHICLE_MAKE_CODE,VEHICLE_MAKE_DESC?,VTC_TYPE_CODE?)+>
  <!ELEMENT VEHICLE_MAKE_CODE (#PCDATA)>
  <!ELEMENT VEHICLE_MAKE_DESC (#PCDATA)>
  <!ELEMENT VTC_TYPE_CODE (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ABAR</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ABARTH DIVISION OF FIAT CHRYSLER AUTOMOBILES</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ACA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC></VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE></VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ACAD</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ACADIAN GM OF CANADA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>COBR</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AC COBRA&#40;COBR&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ACUR</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ACURA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ADET</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ADETTE</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AERA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AEROCAR</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AETA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AETA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ALFA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ALFA ROMEO DIVISION OF FIAT CHRYSLER AUTOMOBILES</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ALLA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ALLARD</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ALCI</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ALLEN COACHWORKS INC</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ALLF</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ALLISONS FIBERGLASS MFG INC</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ALLS</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ALL STATE</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ALMA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ALMA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ALPI</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ALPINE</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ALTA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ALTA OR ALTA CAR AND ENGINEERING CO&#37;UNITED KINGDOM</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ALVI</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ALVIS</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AMER</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AMERICAN MOTORS&#37;&#37;SEE MAKE RAMBLER FOR RAMBLERS MANUFACTURED PRIOR TO 1966</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AMPH</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AMPHICAR</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ARGO</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ARGONAUT STATE LIMOUSINE&#40;ARGO&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ARIT</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ARISTA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ARMS</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ARMSTRONG SIDDELEY</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ARNO</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ARNOLT-BRISTOL&#40;ARNO&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ASA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ASA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ARSC</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ASCORT</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ASHL</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ASHLEY</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ASVE</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ASSEMBLED VEHICLE SEE OPER MAN FOR DESCRIPTION</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ASTO</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ASTON-MARTIN&#40;ASTO&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ASUN</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ASUNA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE></VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AUBU</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AUBURN</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AUDI</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AUDI</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AURR</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AURORA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AUST</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AUSTIN</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AUHE</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AUSTIN HEALY</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AUTA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AUTOBIANCHI</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AUTB</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AUTOBIEU</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AUTO</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AUTOCAR&#40;AUTO&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AUTR</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AUTOCARRIER AND A C</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AUKR</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AUTOKRAFT</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AUTU</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AUTO UNION</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AVTI</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AVANTI</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AVEN</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AVENGER</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>AVIA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AVIA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BNTM</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>AMERICAN BANTAM&#37; PREV AMERICAN AUSTIN</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BEAD</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BEARDMORE</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BEDF</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BEDFORD</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BENT</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BENTLEY</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BERG</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BERGANTINE</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BERK</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BERKLEY</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BERO</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BERTONE&#40;BERO&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BITT</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BITTER</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BIZZ</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BIZZARRINI</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BMW</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BMW</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BOBB</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BOBBI-KAR&#40;BOBB&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BOCA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BOCAR&#40;BOCA&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BOND</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BOND&#40;BOND&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BORG</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BORGWARD&#40;BORG&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BRDL</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BRADLEY GT</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BRAS</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BRASINCA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BREM</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BREMEN SPORT EQUIPMENT INC&#37;BREMEN IN</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BRIC</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BRICKLIN</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BRIS</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BRISTOL</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BUGA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BUGATTI</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BUIC</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BUICK</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BUTT</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>BUTTERFIELD MUSKETEER</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>BZEL</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>B AND Z ELECTRIC CAR CO</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CADI</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CADILLAC</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CHAI</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CHAIKA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CHEC</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CHECKER</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CHEV</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CHEVROLET</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CHIN</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CHING KAN SHAN</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CHRY</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CHRYSLER PART OF FCA US LLC</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CISI</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CISITALIA&#37;CONSORZIO INDUSTRIALE SPORTIVA ITALIA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CITR</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CITROEN</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CITI</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CITICAR&#37; ELECTRIC CAR</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CLAI</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CLASSIC MOTOR CARRIAGES INC&#37;HALLANDALE FL</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CLAC</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CLASSIC ROADSTERS LTD</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CLUA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CLUA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CLEN</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CLENET COACH WORKS</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>COMV</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>COMMUTER VEHICLES, INC.&#40;COMV&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>COCP</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CONCEPTOR INDUSTRIES INC&#40;COCP&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE></VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CONN</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CONNAUGHT&#40;CONN&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CONU</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CONSULIER&#40;CONU&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE></VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CONS</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CONTESSA&#40;CONS&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>COOP</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>COOPER&#40;COOP&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CORD</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CORD&#40;CORD&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CROF</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CROFTON&#40;CROF&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CROS</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CROSLEY&#40;CROS&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CUBS</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CUBSTER</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>CUNN</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>CUNNINGHAM</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DAF</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DAF</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DAIH</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DAIHATSU</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DAIM</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DAIMLER</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DAIN</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>D AND A VEHICLES INC</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DATS</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DATSUN</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DAVI</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DAVIS</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DAYO</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DAYTONA&#40;DAYO&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DB&#9;D</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>B.</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE></VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DEBO</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DEBONAIR&#40;DEBO&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DECO</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DECOURVILLE&#40;DECO&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DEEP</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DEEP SANDERSON</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DELL</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DELLOW</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DELO</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DE LOREAN&#40;DELO&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DENZ</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DENZEL</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DESO</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DESOTO&#40;DESO&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DETO</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DETOMASO&#40;DETO&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DITE</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DI TELLA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DIVA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DIVA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DKW</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DKW</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DODG</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DODGE&#40;DODG&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DONG</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DONG&#40;DONG&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DUEL</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DUEL</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DUES</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DUESENBERG</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>DURA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>DURANT</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>EGIL</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>EAGLE PART OF FCA US LLC</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>EDSE</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>EDSEL</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ELVC</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ELECTRIC VEHICLE CORP&#37; MFRS REPLICAS; MINNEAPOLIS,MN</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE></VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ELVA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ELVA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE></VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>EMW</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>EMW</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE></VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ENGF</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ENGLISH FORD&#37; BRITISH</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ERSK</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ERSKINE</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ESHL</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ESHELMAN SPORTABOUT</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ESSE</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ESSEX</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>EVRY</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>EVERYBODY&#39;S MOTOR CAR MFG.</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ENVY</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ENVOY</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>ENZM</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>ENZMANN</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>EXCL</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>EXCALIBUR</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>FACL</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>FACELLIA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>FACE</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>FACEL-VEGA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>FAIR</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>FAIRTHORPE</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>FALC</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>FALCON&#37; BRITISH</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>FELB</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>FELBER</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>FERR</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>FERRARI</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>FIAA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>FIAT ABARTH PART OF FIAT CHRYSLER AUTOMOBILES</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>FIAT</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>FIAT PART OF FCA US LLC</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>FIBE</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>FIBERFAB, INC&#37; MINNEAPOLIS, MN</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>FIST</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>FIESTA &#40;IMPORTED BY FORD&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>FNM</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>FNM</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>FORD</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>FORD&#40;FORD&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>FRAN</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>FRANKLIN</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>FRNA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>FRAZER-NASH</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>FRAZ</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>FRAZIER</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>FREF</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>FRENCH FORD</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>FRIS</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>FRISKY</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>GMC</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>GENERAL MOTORS CORP.</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>GLAS</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>GLAS</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>GILB</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>GILBERN</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>GINE</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>GINETTA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>GITA</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>GITANE</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>GOLI</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>GOLIATH&#40;GOLI&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>GORD</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>GORDON&#40;GORD&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>GRAC</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>GRACIELA</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>GRAH</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>GRAHAM</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>GRAP</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>GRAHAM-PAIGE</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>GRIF</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>GRIFFITH</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>GSM</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>GSM</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>HEIN</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>HEINKEL</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>HENR</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>HENRY J.</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>HILL</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>HILLMAN</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>HIND</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>HINDUSTAN</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>HINO</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>HINO&#40;HINO&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>HOLD</VEHICLE_MAKE_CODE>
    <VEHICLE_MAKE_DESC>HOLDEN&#40;HOLD&#41;</VEHICLE_MAKE_DESC>
    <VTC_TYPE_CODE>AT</VTC_TYPE_CODE>
  </DATA_RECORD>
  <DATA_RECORD>
    <VEHICLE_MAKE_CODE>HORC</VEHICLE_MAKE_CODE>