<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (TYPE_CODE,TYPE_DESC?)+>
  <!ELEMENT TYPE_CODE (#PCDATA)>
  <!ELEMENT TYPE_DESC (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <TYPE_CODE>AT</TYPE_CODE>
    <TYPE_DESC>Automobile / Passenger</TYPE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <TYPE_CODE>CN</TYPE_CODE>
    <TYPE_DESC>Construction</TYPE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <TYPE_CODE>CY</TYPE_CODE>
    <TYPE_DESC>Motorcycle</TYPE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <TYPE_CODE>FR</TYPE_CODE>
    <TYPE_DESC>Farm</TYPE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <TYPE_CODE>TK</TYPE_CODE>
    <TYPE_DESC>Truck/SUV</TYPE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <TYPE_CODE>TR</TYPE_CODE>
    <TYPE_DESC>Trailer/RVs</TYPE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <TYPE_CODE>XX</TYPE_CODE>
    <TYPE_DESC>Other Misc. vehicles</TYPE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <TYPE_CODE>EM</TYPE_CODE>
    <TYPE_DESC>Emergency Vehicle</TYPE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <TYPE_CODE>PL</TYPE_CODE>
    <TYPE_DESC>Airplane</TYPE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <TYPE_CODE>BO</TYPE_CODE>
    <TYPE_DESC>Boat</TYPE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <TYPE_CODE>MO</TYPE_CODE>
    <TYPE_DESC>Moped</TYPE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <TYPE_CODE>BI</TYPE_CODE>
    <TYPE_DESC>Bicycle</TYPE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <TYPE_CODE>AV</TYPE_CODE>
    <TYPE_DESC>ATV</TYPE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <TYPE_CODE>SN</TYPE_CODE>
    <TYPE_DESC>Snowmobile</TYPE_DESC>
  </DATA_RECORD>
  <DATA_RECORD>
    <TYPE_CODE>GC</TYPE_CODE>
    <TYPE_DESC>Golf Cart</TYPE_DESC>
  </DATA_RECORD>
</main>
