<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (CODE_TYPE,CODE,DESCRIPTION?)+>
  <!ELEMENT CODE_TYPE (#PCDATA)>
  <!ELEMENT CODE (#PCDATA)>
  <!ELEMENT DESCRIPTION (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_DAMAGE_CODES</CODE_TYPE>
    <CODE>00</CODE>
    <DESCRIPTION>None/None known</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_DAMAGE_CODES</CODE_TYPE>
    <CODE>01</CODE>
    <DESCRIPTION>Burned</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_DAMAGE_CODES</CODE_TYPE>
    <CODE>10</CODE>
    <DESCRIPTION>Under Carriage</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_DAMAGE_CODES</CODE_TYPE>
    <CODE>11</CODE>
    <DESCRIPTION>Total &#40;All Areas&#41;</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_DAMAGE_CODES</CODE_TYPE>
    <CODE>12</CODE>
    <DESCRIPTION>Other</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_DAMAGE_CODES</CODE_TYPE>
    <CODE>99</CODE>
    <DESCRIPTION>Unknown</DESCRIPTION>
  </DATA_RECORD>
  <DATA_RECORD>
    <CODE_TYPE>VEHICLE_DAMAGE_CODES</CODE_TYPE>
    <CODE>Code_water</CODE>
    <DESCRIPTION>Water Damage</DESCRIPTION>
  </DATA_RECORD>
</main>
